In [55]:
# import statements
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

In [33]:
# Assign the data to predictor and outcome variables
train_data = pd.read_csv("data.csv",delimiter=',',header=None)

           0        1         2        3        4        5         6
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590  12.31798
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640  23.67628
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626  -1.53459
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084 -24.68670
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022  17.54122
..       ...      ...       ...      ...      ...      ...       ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386  26.14768
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617   0.76214
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655 -10.05262
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519 -19.63970
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444  12.76193

[100 rows x 7 columns]

In [68]:
train_data.iloc[:,:-1]

           0        1         2        3        4        5
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022
..       ...      ...       ...      ...      ...      ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444

[100 rows x 6 columns]

In [69]:
X = train_data.iloc[:,:6]
y= train_data.iloc[:,[-1]]

In [73]:
X

           0        1         2        3        4        5
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022
..       ...      ...       ...      ...      ...      ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444

[100 rows x 6 columns]

In [62]:
# TODO: Create the standardization scaling object.
scaler = StandardScaler()

StandardScaler(copy=True, with_mean=True, with_std=True)

In [77]:
# TODO: Fit the standardization parameters and scale the data.
X_scaled = scaler.fit_transform(X)

In [78]:
# TODO: Create the linear regression model with lasso regularization.
lasso_reg = Lasso()

In [79]:
# TODO: Fit the model.
lasso_reg.fit(X_scaled,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [80]:
# TODO: Retrieve and print out the coefficients from the regression model.
reg_coef = lasso_reg.coef_
print(reg_coef)

[  0.           3.90753617   9.02575748  -0.         -11.78303187
   0.45340137]